apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsproject-deployment
  labels:
    app: devopsproject
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devopsproject
  template:
    metadata:
      labels:
        app: devopsproject
    spec:
      containers:
      - name: devopsproject
        image: karunya08/devopsproject:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: devopsproject-service
spec:
  selector:
    app: devopsproject
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
